### ISSUE TITLE
Out-of-style moduledoc

### ISSUE THREAD

**Issue by Chatatata** [itucsdb1626/itucsdb1626#9]
The moduledoc is not a complete sentence, obfuscating and out-of-style.

```
def add_friend(self, second_user):
    """
    add or update relevant relationship information about two given users
    """
```

**Comment by muratcansahin** [comment]
Fixed https://github.com/itucsdb1626/itucsdb1626/pull/13.

**Comment by Chatatata** [comment]
Closed https://github.com/itucsdb1626/itucsdb1626/pull/13.
